// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCSH4srfSO8B37QrPZFkwME-3M2yixQ28',
    appId: '1:353224481165:web:39f57bfb823af345dc45c4',
    messagingSenderId: '353224481165',
    projectId: 'study-app-project-b111b',
    authDomain: 'study-app-project-b111b.firebaseapp.com',
    storageBucket: 'study-app-project-b111b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMkI8E3CSejRCEWifzHsnqrgaODimSB2g',
    appId: '1:353224481165:android:f4b3ca5b4b84e61ddc45c4',
    messagingSenderId: '353224481165',
    projectId: 'study-app-project-b111b',
    storageBucket: 'study-app-project-b111b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKkdFgnTsix8PT1mL264vz2fEgTWZQ048',
    appId: '1:353224481165:ios:94c15f4f95d0c690dc45c4',
    messagingSenderId: '353224481165',
    projectId: 'study-app-project-b111b',
    storageBucket: 'study-app-project-b111b.appspot.com',
    iosClientId: '353224481165-v5736cbs25p5p9gtvrtt7nm617bm34ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAppProjectTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKkdFgnTsix8PT1mL264vz2fEgTWZQ048',
    appId: '1:353224481165:ios:94c15f4f95d0c690dc45c4',
    messagingSenderId: '353224481165',
    projectId: 'study-app-project-b111b',
    storageBucket: 'study-app-project-b111b.appspot.com',
    iosClientId: '353224481165-v5736cbs25p5p9gtvrtt7nm617bm34ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAppProjectTutorial',
  );
}
